Json server, tasks service and toast messages
zaleskid/kanban pull request #2
Opened 2021-07-29 10:47 UTC by Zaben-dev

2021-07-29 10:48 UTC, Kondzik998 approved these changes

2021-07-29 16:33 UTC, mateciszewski requested changes

2021-07-29 16:33 UTC, mateciszewski commented on src/app/modules/board/client/tasks-client.service.ts
> +    private snackBarService: SnackBarService
TasksClient powinien tylko zawierać logikę komunikacji z backendem, a takie ogólne błędy najlepiej wyłapać wykorzystując do tego http interceptory => https://angular.io/guide/http#intercepting-requests-and-responses

Gdy jednak chcemy obsłużyć jakieś konkretne błędy zapytań http to najlepszym miejscem jest fasada. Gdy zaimplementujemy w warstwie Client wtedy mamy lekkiego sztywniaka i nie będzie dało się już takiego błędu obsłużyć w inny sposób np. w innym widoku który wykorzystuje tego samego clienta ale chciałby wyświetlić nie snackbar a modal, nie ominiemy tego snackbara gdybyśmy chcieli dla jakiegoś zapytania go nie pokazywać.

2021-07-29 16:33 UTC, mateciszewski commented on src/app/core/models/task.ts
> +}
columnId zbyt mało mówi o zadaniu.

Zadanie jest w statusie "In progress" więc zadanie powinno mieć pole status, które jest enumem i może być użyte w aplikacji jako identyfikator kolumny

2021-07-29 16:33 UTC, mateciszewski commented on src/app/core/models/task.ts
> +export interface Task {
Użyj od razu zapisu który pokazywałem na callach

```
 export interface Task extends Readonly<{
      title: string;
      description: string;
      status: number;
      id?: number;
}> {}
```

Wymusza niemutowalność tego obiektu

2021-07-29 16:33 UTC, mateciszewski commented on src/app/modules/board/client/tasks-client.service.ts
> +      .post<Task[]>(this.apiURL, task)
Czy tu jest podany dobry typ zwrotny posta? <Task[]> ?

tak samo przy patch i delete

Przy okazji warto było lepiej otypować kod, tak żeby było jawnie pokazane co zwracają wszystkie metody w tym PR

2021-07-29 16:33 UTC, mateciszewski commented on src/environments/environment.ts
> +  apiURL: 'http://localhost:3000/tasks/',
Tu powinno być bardziej ogólnie
apiURL: 'http://localhost:3000'

a dokładne ścieżki ('/tasks') doklejane w Client'ach

Załóżmy że może być więcej API niż /tasks

2021-07-29 16:33 UTC, mateciszewski commented on src/app/modules/board/client/tasks-client.service.ts
> +  private apiURL = environment.apiURL;
```suggestion
  private apiURL = `${environment.apiURL}/tasks;
```
wyjaśnienie niżej \/ w environment.ts

2021-07-30 08:51 UTC, Zaben-dev commented on src/app/modules/board/client/tasks-client.service.ts
> +    private snackBarService: SnackBarService
dodałem interceptor który przechwytuje ogólne błędy

2021-07-30 10:04 UTC, merged